### ISSUE TITLE
How'd you get blocknotes to work with next?

### ISSUE THREAD

**Issue by Nostromos** [Osadhi/jotion#228]
I'm getting a type error with it ('plugins') and I can't tell what you've done differently in the editor.

Did you come across this issue when you were building it?

**Comment by SourceCodeDeleted** [comment]
I think I had this before when I didn't have my convex backend set up correctly. Try that.

**Comment by Nostromos** [comment]
I'm not doing this tutorial, so there's no convex backend. I'm building something separately that uses it. Thanks anyway though.

I'm closing this out as the most recent Blocknote update fixes my issue.
